sonar.projectKey=clinica_frontend
sonar.projectName=Clinica Frontend
sonar.sourceEncoding=UTF-8
sonar.token=sqp_83b370b30edd4c74f6e43b25f3e835c2a5eda2a7
sonar.host.url=http://localhost:9000

# Código fuente
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**

# Tests
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Coverage
sonar.javascript.lcov.reportPaths=coverage/frontend-clinica/lcov.info
